[package]
name = "phoronix-reader"
version = "0.1.0"
authors = ["Arash Mousavi <mousavi.arash@gmail.com>"]
edition = "2018"

[dependencies]
select = "*"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
hyper-tls = "*"
ansi_term = "0.9"
reqwest="0.9"
